# 导入基础配置
includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml

# 训练设置
epoch: 60  # 论文中使用60轮
test_epoch: 5
episode_size: 1
train_episode: 100
test_episode: 600
way_num: 5
shot_num: 1
query_num: 15
test_way: 5
test_shot: 1
test_query: 15

# 模型设置
backbone:
  name: resnet12  # 使用现有的resnet12
  kwargs:
    avg_pool: True
    is_flatten: True

classifier:
  name: FDAlign
  kwargs:
    feat_dim: 640  # resnet12特征维度
    num_class: 64
    inner_param:
      temperature: 0.1
      adaptation_steps: 100
      lr: 0.01
      n_templates: 60  # SPC参数
      n_clusters: 20   # SPC参数
      optimizer:  # 内部优化器配置
        name: SGD
        kwargs:
          lr: 0.01
          momentum: 0.9
          weight_decay: 0.0005

# 优化器设置
optimizer:
  name: SGD  # 论文使用SGD
  kwargs:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.5
    step_size: 20