includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/clip_vit.yaml

# Model configs
backbone:
  name: CLIPViT
  kwargs:
    model_name: ViT-B/32
    
classifier:
  name: FDAlign
  kwargs:
    feat_dim: 512
    num_class: 64
    alpha: 1.0
    beta: 20.0
    templates:
      - "a photo of a {}"
      - "a photograph of a {}"
      - "an image of a {}"

# Data configs
image_size: 224
use_memory: False
augment: True
augment_times: 1
augment_times_query: 1

# Training configs
epoch: 60
test_epoch: 5
way_num: 5
shot_num: 5
query_num: 15
train_episode: 1000
test_episode: 600

optimizer:
  name: SGD
  kwargs:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001
  
lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.5
    step_size: 20 